# Generated by Django 4.0 on 2022-01-27 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tv_series_name', models.CharField(blank=True, max_length=100, null=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'TVSeries',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.IntegerField(blank=True, null=True)),
                ('tv_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvseries.tvseries')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.IntegerField(blank=True, null=True)),
                ('episode_theme', models.CharField(blank=True, max_length=50, null=True)),
                ('episode_video', models.FileField(blank=True, null=True, upload_to='tvseries/episode_videos/')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tvseries.season')),
            ],
        ),
    ]
