# Generated by Django 4.0 on 2022-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvseries',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
