# Generated by Django 4.0 on 2022-01-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0002_tvseries_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
