# Generated by Django 4.0 on 2022-02-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0004_episode_language_episode_parental_gardian_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='released',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='premiere',
            field=models.DateField(),
        ),
    ]
