# Generated by Django 4.0 on 2022-02-01 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0006_alter_episode_released_alter_tvseries_premiere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='released',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='premiere',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
