# Generated by Django 4.0 on 2022-02-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0010_alter_episode_released'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='released',
        ),
    ]
