# Generated by Django 4.0 on 2022-02-01 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvseries', '0011_remove_episode_released'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='released',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
