# Generated by Django 4.0 on 2022-01-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_episode_tv_series_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='season',
            new_name='tv_series',
        ),
        migrations.AddField(
            model_name='season',
            name='seaoson',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
