# Generated by Django 4.0 on 2022-01-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_season_season_tv_series_season_seaoson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='seaoson',
            new_name='season',
        ),
    ]
