# Generated by Django 4.0 on 2022-01-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_rename_seaoson_season_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviegenre',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
