# Generated by Django 4.0 on 2022-01-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_moviegenre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviegenre',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='Category safe URL'),
        ),
    ]
