# Generated by Django 4.0 on 2022-02-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_remove_season_tv_series_delete_episode_delete_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
